### PR TITLE
Fix suggester tests for JDK9+

### PR DESCRIPTION
**Pull request by Orviss**
Hello,

I completely forgot that web module should contain the profile instead of the indexer module :)

Thanks :)

### CODE REVIEW

**Comment by vladak** [comment]
Looks like Sonar does not like pull requests I've just fixed this in master. Could you rebase/merge with upstream/master pls.

**Comment by Orviss** [comment]
> Looks like Sonar does not like pull requests I've just fixed this in master. Could you rebase/merge with upstream/master pls.

Sure, done.

**Comment by vladak** [comment]
the macOS build is still failing with:
```
[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report (default-cli) on project opengrok-top: Execution default-cli of goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report failed: A required class was missing while executing org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report: javax/xml/bind/DatatypeConverter
```

**Comment by Orviss** [comment]
It passed in my repo: <https://travis-ci.org/Orviss/OpenGrok/jobs/411580996>

**Comment by vladak** [comment]
So, what is the `javax/xml/bind/DatatypeConverter` class and where it is used ? There might be some differences between feature branch builds and pull request builds so I'd like to know what is going on before merging this in.

**Comment by vladak** [comment]
https://github.com/http-kit/http-kit/issues/356 suggests to use `--add-modules java.xml.bind`

**Comment by Orviss** [comment]
Probably coveralls plugin does not play well with Java9+. Still, we use the newest version. I can look at it in the evening :)

**Comment by vladak** [comment]
Also: https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

**Comment by Orviss** [comment]
https://github.com/trautonen/coveralls-maven-plugin/issues/112

**Comment by Orviss** [comment]
I cannot use the trick by adding dependency to `jaxb-api` since `<plugin>` in `<reporting>` cannot have `<dependency>` (<https://maven.apache.org/guides/mini/guide-configuring-plugins.html>).

**Comment by vladak** [comment]
So, the only way is to wait for the Maven Coveralls plugin to be fixed ?

**Comment by Orviss** [comment]
The plugin probably won't be fixed since it is almost 2 years since last commit to the coveralls plugin repository. Plus I don't see any configuration parameter where I would pass `--add-modules java.xml.bind` - something similar to `argLine` of `surefire-plugin` would be nice.

**Comment by tarzanek** [comment]
rebasing, since I'd like to see stuff work with jdk11 as compiler and 1.8 as target

**Comment by vladak** [comment]
Could you rebase this on upstream/master ?

And maybe split the macOS changes into separate PR ?

**Comment by vladak** [comment]
Also, some jaxb dependencies were addressed by cset fd8f155e74a65d233c5e99ff020d4d2f1c8ba445.
