### ISSUE TITLE
Internal Server Error (500) on 1.12.18 (and 1.12.16)

### ISSUE THREAD

**Issue by shyoshiz** [oracle/opengrok#4426]
We get Internal Server Error (500) with 1.12.18 (and 1.12.16).
Our usage is non-project mode. One war file has one branch and there are multiple war files under tomcat.
Assume that all branches (war files) are built with 1.12.17. Next, replace one branch which is build with 1.12.18.
The new branch gets 500 as follows. For the other existing branches, they get blank screen and seem to get 500, too.
We had the same issue on 1.12.16 yesterday. So, I change it back to 1.12.15.
I tried 1.12.17 this morning and it was ok but I have the same issue again on 1.12.18.

RHEL8 / Tomcat: 10.0.2 / JDK: 11.0.2

========
"HTTP Status 500 – Internal Server Error

Type Exception Report

Message Filter execution threw an exception

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

jakarta.servlet.ServletException: Filter execution threw an exception

Root Cause

java.lang.NoClassDefFoundError: Could not initialize class org.opengrok.web.Scripts
	org.opengrok.web.PageConfig.<init>(PageConfig.java:166)
	org.opengrok.web.PageConfig.<init>(PageConfig.java:1599)
	org.opengrok.web.PageConfig.get(PageConfig.java:1582)
	org.opengrok.web.StatisticsFilter.doFilter(StatisticsFilter.java:65)

Note The full stack trace of the root cause is available in the server logs.
Apache Tomcat/10.0.2"
========

**Comment by vladak** [comment]
Is there anything relevant in the logs ?

**Comment by shyoshiz** [comment]
I think this:

10-Oct-2023 08:23:01.439 SEVERE [http-nio-2424-exec-19] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/test01] threw exception [Filter execution threw an exception] with root cause
        java.lang.NoClassDefFoundError: Could not initialize class org.opengrok.web.Scripts
                at org.opengrok.web.PageConfig.<init>(PageConfig.java:166)
                at org.opengrok.web.PageConfig.<init>(PageConfig.java:1599)
                at org.opengrok.web.PageConfig.get(PageConfig.java:1582)
                at org.opengrok.web.StatisticsFilter.doFilter(StatisticsFilter.java:65)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:864)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1655)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:834)
10-Oct-2023 08:23:01.440 SEVERE [http-nio-2424-exec-19] org.apache.catalina.core.ApplicationDispatcher.invoke Servlet.service() for servlet [error] threw exception
        java.lang.NoClassDefFoundError: Could not initialize class org.opengrok.web.Scripts
                at org.opengrok.web.PageConfig.<init>(PageConfig.java:166)
                at org.opengrok.web.PageConfig.<init>(PageConfig.java:1599)
                at org.opengrok.web.PageConfig.get(PageConfig.java:1582)
                at org.apache.jsp.error_jsp._jspService(error_jsp.java:147)
                at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
                at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:770)
                at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:467)
                at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
                at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
                at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:770)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
                at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:692)
                at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:441)
                at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:366)
                at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:294)
                at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:382)
                at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:241)
                at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:336)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:161)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:864)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1655)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:834)
10-Oct-2023 08:23:01.441 SEVERE [http-nio-2424-exec-19] org.apache.catalina.core.StandardHostValve.custom Exception Processing ErrorPage[errorCode=500, location=/error]
        org.apache.jasper.JasperException: An exception occurred processing [/httpheader.jspf] at line [34]

31: 
32:     cfg = PageConfig.get(request);
33:     cfg.setTitle("your title");
34: 
35: </pre>
36: --%>
37: <%@page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" import="


Stacktrace:
                at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:611)
                at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:490)
                at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
                at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
                at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:770)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
                at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:692)
                at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:441)
                at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:366)
                at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:294)
                at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:382)
                at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:241)
                at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:336)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:161)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:864)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1655)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:834)
        Caused by: jakarta.servlet.ServletException: java.lang.NoClassDefFoundError: Could not initialize class org.opengrok.web.Scripts
                at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:674)
                at org.apache.jsp.error_jsp._jspService(error_jsp.java:415)
                at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
                at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:770)
                at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:467)
                ... 26 more
        Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.opengrok.web.Scripts
                at org.opengrok.web.PageConfig.<init>(PageConfig.java:166)
                at org.opengrok.web.PageConfig.<init>(PageConfig.java:1599)
                at org.opengrok.web.PageConfig.get(PageConfig.java:1582)
                at org.apache.jsp.error_jsp._jspService(error_jsp.java:147)
                ... 29 more

**Comment by vladak** [comment]
One thing to try, ideally in staging environment where this can be reproduced, is to make sure all the web apps are deployed are of the same version.

**Comment by shyoshiz** [comment]
We actually do some small modifications to pageheader.jspf and style-1.0.4.(min.)css in source.war. So, I tested again using original source.war. But, we still have the problem. Here are new error messages in browser and new log file contents. I feel the above your guess is right.

HTTP Status 500 – Internal Server Error

Type Exception Report

Message Filter execution threw an exception

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

jakarta.servlet.ServletException: Filter execution threw an exception

Root Cause

java.lang.ExceptionInInitializerError
        org.opengrok.web.PageConfig.<init>(PageConfig.java:166)
        org.opengrok.web.PageConfig.<init>(PageConfig.java:1599)
        org.opengrok.web.PageConfig.get(PageConfig.java:1582)
        org.opengrok.web.StatisticsFilter.doFilter(StatisticsFilter.java:65)

Root Cause

org.webjars.MultipleMatchesException: Multiple matches found for jquery.min.js. Please provide a more specific path, for example by including a version number.
        org.webjars.WebJarAssetLocator.throwMultipleMatchesException(WebJarAssetLocator.java:177)
        org.webjars.WebJarAssetLocator.getFullPath(WebJarAssetLocator.java:235)
        org.webjars.WebJarAssetLocator.getFullPath(WebJarAssetLocator.java:196)
        org.opengrok.web.Scripts.putFromWebJar(Scripts.java:136)
        org.opengrok.web.Scripts.<clinit>(Scripts.java:113)
        org.opengrok.web.PageConfig.<init>(PageConfig.java:166)
        org.opengrok.web.PageConfig.<init>(PageConfig.java:1599)
        org.opengrok.web.PageConfig.get(PageConfig.java:1582)
        org.opengrok.web.StatisticsFilter.doFilter(StatisticsFilter.java:65)

Note The full stack trace of the root cause is available in the server logs.
Apache Tomcat/10.0.2


11-Oct-2023 09:30:04.690 SEVERE [http-nio-2424-exec-8] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/test01] threw exception [Filter execution threw an exception] with root cause
        org.webjars.MultipleMatchesException: Multiple matches found for jquery.min.js. Please provide a more specific path, for example by including a version number.
                at org.webjars.WebJarAssetLocator.throwMultipleMatchesException(WebJarAssetLocator.java:177)
                at org.webjars.WebJarAssetLocator.getFullPath(WebJarAssetLocator.java:235)
                at org.webjars.WebJarAssetLocator.getFullPath(WebJarAssetLocator.java:196)
                at org.opengrok.web.Scripts.putFromWebJar(Scripts.java:136)
                at org.opengrok.web.Scripts.<clinit>(Scripts.java:113)
                at org.opengrok.web.PageConfig.<init>(PageConfig.java:166)
                at org.opengrok.web.PageConfig.<init>(PageConfig.java:1599)
                at org.opengrok.web.PageConfig.get(PageConfig.java:1582)
                at org.opengrok.web.StatisticsFilter.doFilter(StatisticsFilter.java:65)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:864)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1655)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:834)
11-Oct-2023 09:30:04.709 SEVERE [http-nio-2424-exec-8] org.apache.catalina.core.ApplicationDispatcher.invoke Servlet.service() for servlet [error] threw exception
        java.lang.NoClassDefFoundError: Could not initialize class org.opengrok.web.Scripts
                at org.opengrok.web.PageConfig.<init>(PageConfig.java:166)
                at org.opengrok.web.PageConfig.<init>(PageConfig.java:1599)
                at org.opengrok.web.PageConfig.get(PageConfig.java:1582)
                at org.apache.jsp.error_jsp._jspService(error_jsp.java:147)
                at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
                at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:770)
                at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:467)
                at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
                at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
                at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:770)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
                at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:692)
                at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:441)
                at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:366)
                at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:294)
                at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:382)
                at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:241)
                at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:336)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:161)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:864)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1655)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:834)
11-Oct-2023 09:30:04.710 SEVERE [http-nio-2424-exec-8] org.apache.catalina.core.StandardHostValve.custom Exception Processing ErrorPage[errorCode=500, location=/error]
        org.apache.jasper.JasperException: An exception occurred processing [/httpheader.jspf] at line [34]

31: 
32:     cfg = PageConfig.get(request);
33:     cfg.setTitle("your title");
34: 
35: </pre>
36: --%>
37: <%@page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" import="


Stacktrace:
                at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:611)
                at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:490)
                at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
                at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
                at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:770)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
                at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:692)
                at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:441)
                at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:366)
                at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:294)
                at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:382)
                at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:241)
                at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:336)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:161)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:864)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1655)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:834)
        Caused by: jakarta.servlet.ServletException: java.lang.NoClassDefFoundError: Could not initialize class org.opengrok.web.Scripts
                at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:674)
                at org.apache.jsp.error_jsp._jspService(error_jsp.java:401)
                at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
                at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:770)
                at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:467)
                ... 26 more
        Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.opengrok.web.Scripts
                at org.opengrok.web.PageConfig.<init>(PageConfig.java:166)
                at org.opengrok.web.PageConfig.<init>(PageConfig.java:1599)
                at org.opengrok.web.PageConfig.get(PageConfig.java:1582)
                at org.apache.jsp.error_jsp._jspService(error_jsp.java:147)
                ... 29 more

**Comment by vladak** [comment]
This confirms my hypothesis:
```
org.webjars.MultipleMatchesException: Multiple matches found for jquery.min.js. Please provide a more specific path, for example by including a version number.
```
The `Scripts` class in that static block invokes the `getFullPath()` method of a `WebJarAssetLocator` instance to find the file specified with a file name, in the `.jar` files found within the webapp deployment directory. The `.jar` file that contains `jquery.min.js` is located in `WEB-INF/lib/jquery-3.6.4.jar` for the latest OpenGrok version. In the build it comes from here: https://github.com/oracle/opengrok/blob/a8851abcd9791357806af966e37f2323af2861d7/opengrok-web/pom.xml#L108-L112
The version was updated in 6bba31e from 3.6.0 to 3.6.4.

How many `jquery*.jar` files do you see in your deployment that experiences this problem ?

**Comment by shyoshiz** [comment]
I'm now running test environment. I have only 2 war files under /webapps. One is from 1.12.17 and another is 1.12.18 as follows:

>find . -name jquery*.jar
./test02/WEB-INF/lib/jquery-3.6.0.jar
./test01/WEB-INF/lib/jquery-3.6.4.jar

**Comment by vladak** [comment]
> I'm now running test environment. I have only 2 war files under /webapps. One is from 1.12.17 and another is 1.12.18 as follows:
> 
> > find . -name jquery*.jar
> > ./test02/WEB-INF/lib/jquery-3.6.0.jar
> > ./test01/WEB-INF/lib/jquery-3.6.4.jar

`WebJarAssetLocator` used to get the `jquery.min.js` file finds both of these files even though they belong to separate web apps and does like it. Hence, my suggestion to unify the version of all webapps within the same application server still stands.

**Comment by shyoshiz** [comment]
My understanding is this issue occurs because different versions of jquery.jar (jquery-3.6.0.jar and jquery-3.6.4.jar) exist under the same webapps directory because 1.12.17 uses jquery-3.6.0.jar and 1.12.18 uses jquery-3.6.4.jar. Correct?

Then, how often do you upgrade jquery.jar? Do you always upgrade jquery.jar every time you issue new OpenGrok release?

I want to know that this situation always occurs when you issue new releases in future. For example, if the next coming 1.12.19 will still use jquery-3.6.4.jar (this means we will have both 1.12.18 and 1.12.19 mixed under webapps), will we have this issue again even with no different version of jquery.jar exist?

**Comment by vladak** [comment]
That is my understanding as well, however it is not clear to me whether this is the correct/expected behavior. My expectation is that the webjar scanner used by by `org.webjars/jquery` should return the hits for the `META-INF/resources/webjars` path relative to the webapp root, not for the whole application server. This is something to investigate. If the global scan is expected, it might be worthwhile to add version specific path to the `putFromWebJar()` call. This should resolve this problem.

As for the frequency of  `org.webjars/jquery`  updates in OpenGrok, the artifact has much smaller
[version cadency](https://central.sonatype.com/artifact/org.webjars/jquery/versions) than OpenGrok so it is not even technically possible to update it with every OpenGrok release. The other webjar used in scripts, `org.webjars.npm/tablesorter` has even more sparse [version cadency](https://central.sonatype.com/artifact/org.webjars.npm/tablesorter/versions).

**Comment by vladak** [comment]
For a good measure, I decided to follow the rest of the `js` files in that static block of and added version specific paths for all of them to prevent the problem from happening.

**Comment by shyoshiz** [comment]
I finally upgraded (to the latest 1.12.21) and confirmed the fix. Thank you!
