### ISSUE TITLE
reindex endpoint stopped working in 1.7.36

### ISSUE THREAD

**Issue by jwehler** [oracle/opengrok#4066]
**Describe the bug**
Triggering a reindex using the endpoint has stopped working after upgrade from 1.7.35 to 1.7.36.

```
ERROR:start:Exception on /reindex [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/scripts/start.py", line 101, in index
    periodic_timer.notify_all()
AttributeError: 'NoneType' object has no attribute 'notify_all'
```

**To Reproduce**
In my setup:
`docker exec opengrok curl --request GET 'http://localhost:5000/reindex'`

**Comment by vladak** [comment]
Looks like I was sloppy with the global variable handling and general ordering. Thanks for the report !
